### ISSUE TITLE
Resistor R18 Value?

### ISSUE THREAD

**Issue by nsinav** [roybaer/renovation_ssi_2001#3]
Hello. I am trying to get the value of the resistor 0603 R18, but i only get R as value. Can you help me? Thanks.

**Comment by roybaer** [comment]
You can ignore that. The support circuitry around the STM32 was designed with both, filtered PWM output or, alternatively, S/PDIF output in mind, but actually, neither has been implemented so far. R18 would have been there to tune the output level.
I.e. you either have to write the firmware for the STM32 yourself – ideally based on existing SID emulation code – or omit it entirely and use a real SID or drop-in replacement, instead.
The schematic contains notes on which parts are required for which configuration.
A configuration with MOS 6581, for instance, does not need any SMD components at all, but does need a solder bridge below the socket, if I remember correctly.

**Comment by nsinav** [comment]
Thank you
